### ISSUE TITLE
Thank your work.Please comment,report an error when  training,lack CSLRTransformer() this model.

### ISSUE THREAD

**Issue by showfaker66** [matyasbohacek/spoter#1]
`tested_model = CSLRTransformer(num_classes=args.num_classes, hidden_dim=args.hidden_dim)`

**Comment by matyasbohacek** [comment]
Thank you for reporting the issue! This was a mistake left over from earlier version of the code, is has been now fixed in 02621f49aa1509d4b0ae01f334be5a23b22f353e. Should you have any other issues or feedback, feel free to reach out even at `matyas.bohacek[at]matsworld.io`.
