### ISSUE TITLE
Training on new data

### ISSUE THREAD

**Issue by Hamzah-Luqman** [matyasbohacek/spoter#10]
Do you have the code of extracting the pose information from a video file and outputting it in the same format used in your code?

**Comment by matyasbohacek** [comment]
Thanks for your interest in our work!

To obtain data using Vision API (which was used in our original work, [WACV'22 paper](https://openaccess.thecvf.com/content/WACV2022W/HADCV/papers/Bohacek_Sign_Pose-Based_Transformer_for_Word-Level_Sign_Language_Recognition_WACVW_2022_paper.pdf) ) in the same format, use the Pose Data Annotator app ([Mac App Store](https://apps.apple.com/cz/app/pose-data-annotator/id1551118944), [GitHub with Swift code](https://github.com/thanhdolong/sign-language-recognition-trainer)).

We will be providing more options of pose estimator formats — including example code — soon. Please stay tuned.

If this does not resolve your inquiry, please feel free to re-open the thread.
