### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by JefferyJiang-YF** [matyasbohacek/spoter#9]
Dear sir
![image](https://user-images.githubusercontent.com/60686137/214817193-b634a58b-464a-48e4-96ab-eb75f66dec24.png)

I encountered the above bug during training and found out that the graphics card memory is not enough, the graphics card information is RTX 2070 8GB, please ask what parameters can be adjusted to make my graphics card run properly?

**Comment by matyasbohacek** [comment]
Thanks for your interest in our work!

This looks like a generic CUDA error, unrelated to the SPOTER code as such. Others were able to reproduce our codebase on CUDA, and I just verified this by cloning the repository on a new machine.

Here's a couple of pointers you might find helpful:

- ensure that both your model and data are loaded on the GPU (i.e., you applied `.cuda()` or `.device(torch.device("cuda"))` on both);
- ensure that your CUDA installation matches those supported by your PyTorch version;
- clear GPU cache.

You can find an overview of common issues [here](https://pytorch.org/docs/stable/notes/faq.html). Hope this helps!

If this does not resolve your inquiry, please feel free to re-open the thread.
